//! VM behaviour tests written *in wscript* (PRD §11): every `.wscript`
//! file under `tests/scripts/` (workspace root), asserted against
//! directives embedded in the script:
//!
//! ```text
//! // expect: <exact stdout line>     (repeatable, in order)
//! // exit: <code>                    (default 0)
//! // error: <substring of stderr>    (compile or runtime failure expected)
//! ```
//!
//! All three run **in-process**: the VM's output sink captures script
//! output, `diag_render::Renderer` captures rendered diagnostics, and the
//! exit code is read from the run's outcome rather than a process status.
//! One test per script, generated by `build.rs`, so `cargo test lang_units`
//! selects one and a failure names it.
//!
//! Only `binary_maps_outcomes_to_exit_codes` spawns a process, because the
//! argv → `ExitCode` mapping is the one thing that genuinely needs one.

use std::cell::RefCell;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::rc::Rc;

use wscript_cli::Outcome;
use wscript_cli::diag_render::Renderer;

include!(concat!(env!("OUT_DIR"), "/script_tests.rs"));

fn script_path(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("tests/scripts")
        .join(format!("{name}.wscript"))
}

#[derive(Default)]
struct Expectations {
    lines: Vec<String>,
    exit: u8,
    error: Option<String>,
}

fn expectations(source: &str) -> Expectations {
    let mut e = Expectations::default();
    for line in source.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("// expect:") {
            e.lines
                .push(rest.strip_prefix(' ').unwrap_or(rest).to_string());
        } else if let Some(rest) = line.strip_prefix("// exit:") {
            e.exit = rest.trim().parse().expect("bad `// exit:` directive");
        } else if let Some(rest) = line.strip_prefix("// error:") {
            e.error = Some(rest.trim().to_string());
        }
    }
    e
}

fn check_script(name: &str) {
    let path = script_path(name);
    let source = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let expected = expectations(&source);

    // `PrintHook` is not `Send`, and neither is a `Vm` — one per thread is
    // the model, so an `Rc` sink is the right shape here.
    let captured = Rc::new(RefCell::new(String::new()));
    let sink = captured.clone();
    let mut rendered: Vec<u8> = Vec::new();

    let outcome = {
        let mut err = Renderer::plain(&mut rendered);
        wscript_cli::run_script(
            &path.to_string_lossy(),
            Vec::new(),
            Box::new(move |s: &str, newline: bool| {
                let mut buf = sink.borrow_mut();
                buf.push_str(s);
                if newline {
                    buf.push('\n');
                }
            }),
            &mut err,
        )
    };
    let stderr = String::from_utf8_lossy(&rendered);

    if let Some(needle) = &expected.error {
        assert_ne!(
            outcome,
            Outcome::Exited(0),
            "\n{}: expected failure containing `{needle}`, but the run succeeded",
            path.display()
        );
        assert!(
            stderr.contains(needle.as_str()),
            "\n{}: rendered diagnostics do not contain `{needle}`\n--- rendered ---\n{stderr}",
            path.display()
        );
        return;
    }

    let exit = match outcome {
        Outcome::Exited(code) => code,
        other => panic!(
            "\n{}: expected a clean run, got {other:?}\n--- rendered ---\n{stderr}",
            path.display()
        ),
    };

    let text = captured.borrow();
    let actual: Vec<&str> = text.lines().collect();
    let want: Vec<&str> = expected.lines.iter().map(String::as_str).collect();
    assert_eq!(
        actual,
        want,
        "\n{}: stdout mismatch\n--- expected ---\n{}\n--- actual ---\n{}\n--- rendered ---\n{stderr}",
        path.display(),
        want.join("\n"),
        actual.join("\n")
    );
    assert_eq!(
        exit,
        expected.exit,
        "\n{}: exit code {exit}, expected {}",
        path.display(),
        expected.exit
    );
}

/// The binary's own argv handling and exit-code mapping — the one thing
/// that genuinely needs a process.
#[test]
fn binary_maps_outcomes_to_exit_codes() {
    let bin = env!("CARGO_BIN_EXE_wscript");

    let usage = Command::new(bin).output().expect("spawn");
    assert_eq!(usage.status.code(), Some(2), "no subcommand → usage");

    let version = Command::new(bin).arg("--version").output().expect("spawn");
    assert_eq!(version.status.code(), Some(0));
    assert!(String::from_utf8_lossy(&version.stdout).starts_with("wscript "));

    let missing = Command::new(bin)
        .args(["run", "does-not-exist.wscript"])
        .output()
        .expect("spawn");
    assert_eq!(missing.status.code(), Some(1));

    let ok = Command::new(bin)
        .args(["run", &script_path("m5_process_exit").to_string_lossy()])
        .output()
        .expect("spawn");
    assert_eq!(
        ok.status.code(),
        Some(3),
        "process::exit(3) must reach the process exit status"
    );
}
