[package]
name = "wscript-cli"
description = "wscript command-line interface: run, check, repl, lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wscript"
path = "src/main.rs"

[dependencies]
wscript.workspace = true
wscript-std.workspace = true
wscript-compiler.workspace = true
ariadne = "0.6"
rustyline = "18"
toml = "1"
tower-lsp-server = "0.23"
tokio = { version = "1", features = ["rt-multi-thread", "io-std", "macros"] }

[dev-dependencies]
wscript-vm.workspace = true
