//! `.wispi` interface generation (PRD §9.1): dump every registered
//! module / function / type / const signature as a textual, human-readable,
//! diff-friendly subset of wisp syntax — declarations only, no bodies.
//! The same parser parses it; the LSP and `wisp check` consume it.

use std::fmt::Write;

use wisp_core::defs::{DefId, DefKind, FIRST_FREE_DEF, VariantKind};
use wisp_core::registry::Registry;
use wisp_core::types::{FnSig, Type};

pub fn render(reg: &Registry) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by wisp {} — host interface declarations.\n\
         // Consumed by the LSP and `wisp check` (list this file in wisp.toml).\n\
         // Do not edit by hand.",
        env!("CARGO_PKG_VERSION")
    );

    // Ambient types first (they belong to no namespace; modules may list
    // them, but the declarations live at the top level).
    for (i, def) in reg.defs.defs.iter().enumerate() {
        if (i as u32) < FIRST_FREE_DEF {
            continue;
        }
        let id = DefId(i as u32);
        match def {
            DefKind::Struct(s) if s.host => {
                out.push('\n');
                if s.opaque {
                    let _ = writeln!(out, "#[opaque]\nstruct {} {{}}", s.name);
                } else {
                    let _ = writeln!(out, "struct {} {{", s.name);
                    for (fname, fty) in &s.fields {
                        let _ = writeln!(out, "    {fname}: {},", fty.display(&reg.defs));
                    }
                    let _ = writeln!(out, "}}");
                }
                // Methods (PRD §6.2) render as an impl block of bodyless fns.
                if let Some(methods) = reg.methods.get(&id) {
                    let _ = writeln!(out, "\nimpl {} {{", s.name);
                    for m in methods {
                        if let Some(doc) = &m.doc {
                            for line in doc.lines() {
                                let _ = writeln!(out, "    /// {line}");
                            }
                        }
                        let _ = writeln!(
                            out,
                            "    fn {}({}){}",
                            m.name,
                            sig_params(&m.sig, reg, true),
                            ret_suffix(&m.sig.ret, reg)
                        );
                    }
                    let _ = writeln!(out, "}}");
                }
            }
            DefKind::Enum(e) if e.host => {
                out.push('\n');
                let _ = writeln!(out, "enum {} {{", e.name);
                for v in &e.variants {
                    match v.kind {
                        VariantKind::Unit => {
                            let _ = writeln!(out, "    {},", v.name);
                        }
                        VariantKind::Tuple => {
                            let tys: Vec<String> =
                                v.fields.iter().map(|(_, t)| t.display(&reg.defs)).collect();
                            let _ = writeln!(out, "    {}({}),", v.name, tys.join(", "));
                        }
                        VariantKind::Struct => {
                            let fields: Vec<String> = v
                                .fields
                                .iter()
                                .map(|(n, t)| format!("{n}: {}", t.display(&reg.defs)))
                                .collect();
                            let _ = writeln!(out, "    {} {{ {} }},", v.name, fields.join(", "));
                        }
                    }
                }
                let _ = writeln!(out, "}}");
                if let Some(methods) = reg.methods.get(&id) {
                    let _ = writeln!(out, "\nimpl {} {{", e.name);
                    for m in methods {
                        if let Some(doc) = &m.doc {
                            for line in doc.lines() {
                                let _ = writeln!(out, "    /// {line}");
                            }
                        }
                        let _ = writeln!(
                            out,
                            "    fn {}({}){}",
                            m.name,
                            sig_params(&m.sig, reg, true),
                            ret_suffix(&m.sig.ret, reg)
                        );
                    }
                    let _ = writeln!(out, "}}");
                }
            }
            _ => {}
        }
    }

    for module in &reg.modules {
        out.push('\n');
        if let Some(doc) = &module.doc {
            for line in doc.lines() {
                let _ = writeln!(out, "/// {line}");
            }
        }
        let _ = writeln!(out, "mod {} {{", module.name);
        for (name, ty, value) in &module.consts {
            let shown = match value {
                wisp_core::bytecode::Const::Int(n) => format!(" // = {n}"),
                wisp_core::bytecode::Const::Float(f) => format!(" // = {f}"),
                wisp_core::bytecode::Const::Bool(b) => format!(" // = {b}"),
                wisp_core::bytecode::Const::Char(c) => format!(" // = {c:?}"),
                wisp_core::bytecode::Const::Str(s) => format!(" // = {s:?}"),
                wisp_core::bytecode::Const::Unit => String::new(),
            };
            let _ = writeln!(out, "    const {name}: {}{shown}", ty.display(&reg.defs));
        }
        for (name, sig, _, doc) in &module.fns {
            if let Some(doc) = doc {
                for line in doc.lines() {
                    let _ = writeln!(out, "    /// {line}");
                }
            }
            let _ = writeln!(
                out,
                "    fn {name}({}){}",
                sig_params(sig, reg, false),
                ret_suffix(&sig.ret, reg)
            );
        }
        let _ = writeln!(out, "}}");
    }
    out
}

fn sig_params(sig: &FnSig, reg: &Registry, method: bool) -> String {
    let mut parts: Vec<String> = Vec::new();
    if method {
        parts.push("self".into());
    }
    for (i, p) in sig.params.iter().enumerate() {
        parts.push(format!("a{i}: {}", p.display(&reg.defs)));
    }
    parts.join(", ")
}

fn ret_suffix(ret: &Type, reg: &Registry) -> String {
    if *ret == Type::Unit {
        String::new()
    } else {
        format!(" -> {}", ret.display(&reg.defs))
    }
}
